---
AllCops:
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Exclude: ["test/*.rb"]
